In [1]:
import numpy as np

In [5]:
# 进行向量的相加
def numpysum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 2
    print(a)
    print(b)
    c = a + b
    return c

numpysum(2)

[0 1]
[0 1]


array([0, 2], dtype=int32)

In [10]:
# 创建多维向量
a = np.array([np.arange(2), np.arange(2)])
a

array([[0, 1],
       [0, 1]])

In [8]:
b = np.array([[np.arange(2), np.arange(2)],[np.arange(2), np.arange(2)]])
b

array([[[0, 1],
        [0, 1]],

       [[0, 1],
        [0, 1]]])

In [13]:
# 选取数组元素
a = np.array([[1, 2], [3, 4]])
a[0, 1]

2

In [22]:
# 参数可以指定类型
a = np.arange(7,  dtype='uint32')
a

array([0, 1, 2, 3, 4, 5, 6], dtype=uint32)

In [23]:
# 查看数据类型对象中单个数组元素在内存占用的字节数
a.dtype.itemsize

4

In [29]:
np.dtype('f8')

dtype('float64')

In [46]:
# 切片
a = np.arange(8)
a[3:6], a[::2], a[::-1]

(array([3, 4, 5]), array([0, 2, 4, 6]), array([7, 6, 5, 4, 3, 2, 1, 0]))

In [51]:
# 多维数组的切片和索引
b = np.arange(24).reshape(2, 3, 4)
b.shape, b

((2, 3, 4),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [52]:
b[0,  ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
b[0, 1]

array([4, 5, 6, 7])

In [54]:
b[0, 1, ::2]

array([4, 6])

In [62]:
b[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [56]:
b[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [50]:
b[0, 0, 1], b[:, 0, 1]

(1, array([ 1, 13]))

In [66]:
b[0, ::-1, -1]

array([11,  7,  3])

In [65]:
b[0, :, -1]

array([ 3,  7, 11])

In [67]:
b[0, ::2, -1]

array([ 3, 11])

In [69]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [70]:
# 改变数组的维度
# ravel函数可以展平
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
# flatten 也是展平
# flatter函数会请求分配内存来保存结果
# ravel函数只是返回数组的一个视图
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
# 用元组设置维度
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
# 转置矩阵
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [79]:
# resize函数和reshape一样，但resize会直接修改所操作的数组
b.resize((2, 12))
b.reshape(2, 3 ,4)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [82]:
# 组合数组
c = np.arange(9).reshape(3, 3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [83]:
d = 2 * c
d

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [86]:
# 水平组合，使用hstack函数
np.hstack((c, d))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [89]:
# concatenate函数来实现同样的效果
np.concatenate((c, d), axis = 1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [90]:
# 垂直组合，使用vstack函数
np.vstack((c, d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [91]:
# concatenate函数也可实现这样的效果
np.concatenate((c, d), axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [92]:
#  深度组合
# 将相同的元祖作为参数传给dstack函数，即可完成数组的深度组合
# 深度组合：将一系列数组沿着纵轴（深度）方向进行层叠组合
np.dstack((c, d))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [98]:
# 列组合 
# column_stack函数对于一维数组按排列方向进行组合
# 二维数组与水平排列效果一致
oned = np.arange(2)
twice_oned = 2 * oned
np.column_stack((oned, twice_oned)), np.column_stack((c, d))

(array([[0, 0],
        [1, 2]]),
 array([[ 0,  1,  2,  0,  2,  4],
        [ 3,  4,  5,  6,  8, 10],
        [ 6,  7,  8, 12, 14, 16]]))

In [99]:
# 行组合
# row_stack函数按行方向进行组合
# 对于一维数组，将直接层叠起来组合成一个二维数组
np.row_stack((oned, twice_oned))

array([[0, 1],
       [0, 2]])

In [100]:
# 对于二维数组，与垂直排列效果一致
np.row_stack((c, d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# 数组的分割
# 相关的函数有hsplit、vsplit、dsplit和split

In [109]:
# 水平分割
np.hsplit(c, 3)[0].shape

(3, 1)

In [107]:
# split实现相同效果
np.split(c, 3, axis = 1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [111]:
# 垂直分割
np.vsplit(c, 3)[0].shape

(1, 3)

In [110]:
# split
np.split(c, 3, axis = 0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [115]:
# 深度分割
e = np.arange(27).reshape(3, 3, 3)
e, np.dsplit(e, 3)[0]

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]))

In [118]:
# 数组的属性
a.shape, a.dtype

((8,), dtype('int32'))

In [119]:
a.ndim # 维数

1

In [123]:
a.size # 数组元素的总个数

8

In [124]:
a. itemsize

4

In [122]:
a.nbytes # 整个数组所占的存储空间, 其实就是itemsize和size属性值的乘积

32

In [127]:
e, e.T # 转置

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[[ 0,  9, 18],
         [ 3, 12, 21],
         [ 6, 15, 24]],
 
        [[ 1, 10, 19],
         [ 4, 13, 22],
         [ 7, 16, 25]],
 
        [[ 2, 11, 20],
         [ 5, 14, 23],
         [ 8, 17, 26]]]))

In [129]:
b = np.array([1.j + 1, 2.j + 3])
b, b.real, b.imag

(array([1.+1.j, 3.+2.j]), array([1., 3.]), array([1., 2.]))

In [131]:
#flat属性将返回一个numpy.flatiter对象，
#这是获得flatiter对象的唯一方式——我们无法访问flatiter的构造函数。
b = np.arange(4).reshape(2, 2)
b, b.flat

(array([[0, 1],
        [2, 3]]),
 <numpy.flatiter at 0x1f3d6828090>)

In [134]:
for item in b.flat: 
    print(item)

0
1
2
3


In [136]:
b.flat[2], b.flat[[1, 2]]

(2, array([1, 2]))

In [137]:
# 可赋值
b.flat[2] = 3
b

array([[0, 1],
       [3, 3]])

In [138]:
# 数组转换
# 将numpy数组转换成python列表
b.tolist()

[[0, 1], [3, 3]]

In [143]:
# astype函数可以在转换数组时指定数据类型
b.astype('float32').tolist()

[[0.0, 1.0], [3.0, 3.0]]